language: rust
rust:
- stable
- beta
- nightly
sudo: false
dist: trusty
os:
- linux
- osx
cache:
  directories:
  - "$HOME/.cargo"
  - target
env:
  global:
  - secure: bNl7TewSmQ/wV9BOdonY1+nHrw9DvKu5PeuAkJx4oH3XNadvM/XDydUYsZBl97nkqVEiQf6ghbVkjMioMAFr3905EabtR3AC7jDVHhLUfXrD4qkQ2RYDSgu5vR+A6hQkMy9qD66T1L7Cms2rfDJbbKWI+LGZxEAFcSJjPwwWD1cxG46iGXN9wJAFl/1qWCBUM4DvEtnJEFt6BpJVDpVHNiAxId1vjYe4kTCQbKYCb5jLAjv8zGbmTWrd0VQj1XjCdRuEBRyLqL+egvilJS4SwueGaRqeE4p4AetATsXcErfZNwmQ0FyEuo4NBcJcv1ovOhbOfrVHCI6TA1Hn/ZIO02UfjHtu9rwlrUS9+GcEQAzpvvGPEWdUbiNXHOoer3JxyDku4ACNAvPbtLuWS6joZZLzgZ5uou3MEs8p84/2pppEXeYfRY6CjkP5B9QPPciXsfX1jLIh2f8QoAlSAi+EywAKi37lcnJiWWFbQYbNRS6XINv5aGnqqmzmgBNbzDxbb9aJg/zX3SYPOBRf/deZv+Jg9AY5rsHOxhn/Bh+PgDBl1cPX3fRM0s9WqzT96446+Rww3vQPruvzKvYS4cNG0wCS8yrhbmXfBZDbnf9diLequNx5UEcTSE22GESMNseiQTqlaTi0fYU2biAczGSeVjROXHn3l7+4LDGXNR1ucwE=
  - secure: qYz8YlJfc+XfzXPPanZmIJVvzMH/R8oq+Kb4yn8fBF25W/y8bL+jSciGjbhprCoOGs2ClCL9NaFX1NhIr4joajhxTv02Cjts6CDPNG48OIpBTC8/1DRcdpSf/LVvrx0p+WeIF/yn7HBJfAMReWjl8KBcoaPxA29yDobQ2tM41VlF7fBZXErCojUlldEI8Eyca3HdpTgySU4KnwGoEYrfbmNj7xsO7h1omPekfJ+IF68TKcGW1yK1GYc4cR8wUEr3g+FanfHa+WrIv7pmO8uOrPqvYSaW3DUVEY7tQVWRpiChijALTPkU8cmIqoWjwvAQIvjyJPLhDWym/LH1eqFYsyzBRaoY0TvXCO8MUjoA7SjtRZloSv9mdZWFddF8pXIR96OUyXdKU4vFw34ISgqfGb51PmRlG0xiJCUtSZc33wSQyRNPhc16Jm/PwBv7dXfEv2CLhoXoBTNpFnwasyStnrkAXdIEEH5tYB3zhsoFoRRUwqfRJcbYiaqSZVivXr6Vs2stVXuaOx0CnPallIszPSwYFazSW4TsH62leY3J/aQ2BdjWusWyvU91r/TJNBkNRZveQxBNLpGwVVX2wLZtPjR8iXrUBMhGx3hWcxB1YhLIuBqPckGH5PXmY5DznMBNBYhk80MM3FHfZxbGemcYQhz7jJ/nS9I7JnGyoKl5GJw=
  matrix:
  - CARGO_FEATURES=
  - CARGO_FEATURES=uninitialized
  - UNSAFE_UNINITIALIZED=1
before_script:
- curl -L https://github.com/arcnmx/ci/archive/0.1.tar.gz | tar -xzC $HOME && . $HOME/ci-0.1/src
script:
- cargo test
- cargo build
deploy:
  provider: script
  script: 'true'
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_RUST_VERSION = stable"
before_deploy:
- cargo doc
- cargo package
after_deploy:
- cargo pages-publish
- cargo publish
